name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SVR_IP }}
          username: ${{ secrets.DEPLOY_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.SVR_DIR }}
            git pull
            composer install
            vendor/bin/phpmig migrate
            cd liff
            npm install
            export NODE_OPTIONS="--max-old-space-size=400"
            npm run build
